---
title: "Reproducible Research: Peer Assessment 1"
author: "Steve Orosz"
date: "August 22, 2018"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r load data,  echo=TRUE}
knitr::opts_chunk$set(echo = TRUE)

#Libraries

library(lubridate)
library(dplyr)

#Get file

Mydata <- read.csv("C:/Users/smoro/OneDrive/Desktop/Data Science/John Hopkins University/Reproducible Research/Project_One/activity.csv", header = TRUE)

#Create weekday fields
MydataComplete <- Mydata %>% mutate (weekday = weekdays(as.Date(Mydata$date))) %>% mutate(weekdayNum = wday(Mydata$date))


#Create data set without misssing values and with missing values
WithOut <-  na.exclude(MydataComplete)
With <- MydataComplete


```


## What is mean total number of steps taken per day?
```{r Number of Steps per Day , echo=TRUE}

#Count total steps per day
ts <- tapply(WithOut$steps, WithOut$date , sum, na.rm=T)
TotalStepDay <- data.frame(date = names(ts), sum = ts)

original <- na.exclude(TotalStepDay)


```

```{r Histogram of total steps per day , echo=TRUE}

#Histogram of total steps per day
hist(original$sum, main = "Total Steps Taken per Day", xlab = "Steps")

#Mean number of steps per Day
mean(original$sum)

#Median number of steps per Day
median(original$sum)

```


## What is the average daily activity pattern?
```{r Mean and median number of Steps per Day, echo=TRUE}

IntervalDailyPaterns <- tapply(WithOut$steps, WithOut$interval, mean)

plot(IntervalDailyPaterns ~ unique(WithOut$interval), type="l", xlab = "Interval", ylab = "Number of Steps", main = "Average Daily Activity Pattern")

#Which 5 minute interval, on average, contains maximum number of steps
IntervalDailyPaterns[which.max(IntervalDailyPaterns)]

```



## Imputing missing values

```{r Missing Values, echo=TRUE}
#What is the total number of rows with missing values?
sum(is.na(With$steps))

#Calculate mean per interval of steps. This will be used for NA steps
MeanIntervalNoNA <- tapply(WithOut$steps, WithOut$interval , mean)

CorrectedStep <- data.frame(interval = names(MeanIntervalNoNA), IntervalMean = round(MeanIntervalNoNA))

NeedsFixing <-With %>% filter(is.na(With$steps))

stageFix <- merge(NeedsFixing, CorrectedStep, by = "interval")

corrected <- data.frame(steps = stageFix$IntervalMean,
date = stageFix$date, interval = stageFix$interval, weekday = stageFix$weekday, weekdayNum = stageFix$weekdayNum)

Fixed <- rbind(corrected, WithOut)


```


```{r Histogram of total steps per day for all data , echo=TRUE}

FixedSum <- tapply(Fixed$steps, Fixed$date , sum)
FixedTotalStepDay <- data.frame(date = names(FixedSum), sum = FixedSum)


hist(FixedTotalStepDay$sum, main = "Histogram of total steps per day for Fixed Data")

#Mean number of steps per Day without NA Data
mean(FixedTotalStepDay$sum)
#Mean number of steps per Day with NA fix
mean(original$sum)

#Median number of steps per Day without NA Data
median(FixedTotalStepDay$sum)
#Median number of steps per Day with NA fix
median(original$sum)

#Fixed data
summary(FixedTotalStepDay$sum)
#Original data
summary(original$sum)

```


## Are there differences in activity patterns between weekdays and weekends?


```{r Compare weekdays to weekends , echo=TRUE}

Wkdays <- c("Monday","Tuesday","Wednesday","Thursday","Friday")

weekendText <- c("weekend")
weekdayText <- c("weekday")

wkDayEnd <- Fixed %>% mutate(weekType = ifelse(Fixed$weekday %in% (Wkdays),weekdayText,weekendText))


weekDayData <- wkDayEnd %>% filter(wkDayEnd$weekType == weekdayText)

weekEndData <- wkDayEnd %>% filter(wkDayEnd$weekType == weekendText)

IntervalMeanWeekDay <- tapply(weekDayData$steps, weekDayData$interval, mean)

IntervalMeanWeekEnd <- tapply(weekEndData$steps, weekEndData$interval, mean)

plot(IntervalMeanWeekDay ~ unique(wkDayEnd$interval), type="l", xlab = "Interval", ylab = "Number of Steps", main = "Weekday")

plot(IntervalMeanWeekEnd ~ unique(wkDayEnd$interval), type="l", xlab = "Interval", ylab = "Number of Steps", main = "Weekend")



```

